### PR TITLE
Added gitattributes file to convert CRLF to LF

### PR DESCRIPTION
**Pull request by AleshaOleg**

### CODE REVIEW

**Comment by AleshaOleg** [comment]
Got a warning before committing for tested file: `warning: CRLF will be replaced by LF in web/src/components/index.ts.`. Seems working correctly

**Review by sk7 — CHANGES_REQUESTED** [review]
> Since Git 2.16 (Q1 2018), you can use git add --renormalize . to apply those .gitattributes settings immediately.

https://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows

so I ran `git add --renormalize .` and this changes all woff/woff2/ttf files, so we should either exclude those file types or exclude web/src/fonts/

**Comment by sk7** [comment]
works

**Review by sk7 — APPROVED** [review]

**Comment by sk7** [comment]
was merged, but github crashed and got confused. closing this PR.

**Pull request closed without merging**
