### PR TITLE
GRAPE-19396

### PR DESCRIPTION
**Pull request by AleshaOleg**

### CODE REVIEW

**Review by pseudonymcp — CHANGES_REQUESTED** [review]
- If a text field is invalid, then the help text has an id the text field can reference to via aria-describedby and aria-describedby of the text field connects to the error message.

**Review by pseudonymcp — CHANGES_REQUESTED** [review]
Found some issues:
- font-size inside input is wrong (computed 13.3333px)
- input field with `type=search` is wider than with other types (like number, email, …)
- the `necessityIndicator` prop isn't documented: how to define if "required" and "optional" suffix should be shown or hidden? → "A required or optional field can either be denoted with text added to the end of the label or have no indication at all."
- an input field with `maxLength` should hide the character counter in disabled and read-only state
- props for read-only and disabled state are missing in Storybook Controls and in props documentation

**Review by pseudonymcp — CHANGES_REQUESTED** [review]
Found one small issue with input type and `maxLength`/`minLength` vs `max`/`min`:  

`MaxLength` and `minLength` shouldn't be available for `type=number`, only for all other input types. For number we have `max` and `min` instead (see screenshots).  

textfield-number-max #1


textfield-number-max #2

**Review by pseudonymcp — APPROVED** [review]
Looks good now 👍

**Review by sk7 — APPROVED** [review]

**Pull request merged**
