### PR TITLE
GRAPE-19391

### PR DESCRIPTION
**Pull request by AleshaOleg**

### CODE REVIEW

**Review by pseudonymcp — APPROVED** [review]
Looks good from the visual side! 👍

**Comment by sk7** [comment]
@pseudonymcp  the code is fine, but shouldn pressing Tab on the keyboard not actually highlight the next tab?  this would be the next clickable element, not the link or the button. That's how the tabs in Storybook behave for example, you highlight the next one with Tab and select it by pressing Space

**Review by sk7 — COMMENTED** [review]
asked a question as comment already

**Comment by pseudonymcp** [comment]
@sk7 No, behavior is fine as it is. Tab key should tab from tab list into tabbable element inside tab content. Switching between tabs is with arrow left/right key.

You can also read about keyboard navigation in tabbed interfaces here
https://inclusive-components.design/tabbed-interfaces/

**Pull request merged**
